apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: annual-tortoise-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: annual-tortoise-go 
  name: annual-tortoise-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: annual-tortoise-go 
